name: Scheduled Python Worker

on:
  schedule:
    - cron: '0 20 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 添加手动触发器

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 选择你想要的 Python 版本

      - name: Install Dependencies
        run: pip install packaging requests  # 安装 requests 库

      - name: Run Python Script
        run: python worker.py

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add plugins.json
          git commit -m "Update plugins.json"
          git push
